package DMS_CORBA;

/**
* DMS_CORBA/CommonInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMS_CORBA.idl
* Wednesday, February 22, 2023 6:46:12 o'clock PM EST
*/

public final class CommonInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public DMS_CORBA.CommonInterface value = null;

  public CommonInterfaceHolder ()
  {
  }

  public CommonInterfaceHolder (DMS_CORBA.CommonInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DMS_CORBA.CommonInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DMS_CORBA.CommonInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DMS_CORBA.CommonInterfaceHelper.type ();
  }

}
