package DMS_CORBA;


/**
* DMS_CORBA/CommonInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMS_CORBA.idl
* Wednesday, February 22, 2023 6:46:12 o'clock PM EST
*/

public interface CommonInterface extends CommonInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CommonInterface
