package DMS_CORBA;


/**
* DMS_CORBA/CommonInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMS_CORBA.idl
* Wednesday, February 22, 2023 6:46:12 o'clock PM EST
*/

abstract public class CommonInterfaceHelper
{
  private static String  _id = "IDL:DMS_CORBA/CommonInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, DMS_CORBA.CommonInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DMS_CORBA.CommonInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DMS_CORBA.CommonInterfaceHelper.id (), "CommonInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DMS_CORBA.CommonInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CommonInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DMS_CORBA.CommonInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DMS_CORBA.CommonInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DMS_CORBA.CommonInterface)
      return (DMS_CORBA.CommonInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DMS_CORBA._CommonInterfaceStub stub = new DMS_CORBA._CommonInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DMS_CORBA.CommonInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DMS_CORBA.CommonInterface)
      return (DMS_CORBA.CommonInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DMS_CORBA._CommonInterfaceStub stub = new DMS_CORBA._CommonInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
