package DMS_CORBA;


/**
* DMS_CORBA/CommonInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMS_CORBA.idl
* Wednesday, February 22, 2023 6:46:12 o'clock PM EST
*/

public interface CommonInterfaceOperations 
{
  String addMovieSlots (String movieID, String movieName, int bookingCapacity);
  String removeMovieSlots (String movieID, String movieName);
  String listMovieShowsAvailability (String movieName);
  String bookMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  String getBookingSchedule (String customerID);
  String cancelMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  String exchangeTickets (String customerID, String movieID, String newMovieID, String oldMovieName, String movieName, int numberOfTickets);
} // interface CommonInterfaceOperations
