package frontend.DMS_CORBA;


/**
* DMS_CORBA/ServerObjectInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerObjectInterface.idl
* Monday, April 3, 2023 4:13:55 o'clock PM EDT
*/

public interface ServerObjectInterface extends ServerObjectInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerObjectInterface
