package frontend.DMS_CORBA;

/**
 * DMS_CORBA/ServerObjectInterfaceHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ServerObjectInterface.idl
 * Monday, April 3, 2023 4:13:55 o'clock PM EDT
 */

public abstract class ServerObjectInterfaceHelper {

  private static String _id = "IDL:DMS_CORBA/ServerObjectInterface:1.0";

  public static void insert(org.omg.CORBA.Any a, ServerObjectInterface that) {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
    a.type(type());
    write(out, that);
    a.read_value(out.create_input_stream(), type());
  }

  public static ServerObjectInterface extract(org.omg.CORBA.Any a) {
    return read(a.create_input_stream());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;

  public static synchronized org.omg.CORBA.TypeCode type() {
    if (__typeCode == null) {
      __typeCode =
        org.omg.CORBA.ORB
          .init()
          .create_interface_tc(
            ServerObjectInterfaceHelper.id(),
            "ServerObjectInterface"
          );
    }
    return __typeCode;
  }

  public static String id() {
    return _id;
  }

  public static ServerObjectInterface read(
    org.omg.CORBA.portable.InputStream istream
  ) {
    return narrow(istream.read_Object(_ServerObjectInterfaceStub.class));
  }

  public static void write(
    org.omg.CORBA.portable.OutputStream ostream,
    ServerObjectInterface value
  ) {
    ostream.write_Object((org.omg.CORBA.Object) value);
  }

  public static ServerObjectInterface narrow(org.omg.CORBA.Object obj) {
    if (obj == null) return null; else if (
      obj instanceof ServerObjectInterface
    ) return (ServerObjectInterface) obj; else if (
      !obj._is_a(id())
    ) throw new org.omg.CORBA.BAD_PARAM(); else {
      org.omg.CORBA.portable.Delegate delegate =
        ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
      _ServerObjectInterfaceStub stub = new _ServerObjectInterfaceStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServerObjectInterface unchecked_narrow(
    org.omg.CORBA.Object obj
  ) {
    if (obj == null) return null; else if (
      obj instanceof ServerObjectInterface
    ) return (ServerObjectInterface) obj; else {
      org.omg.CORBA.portable.Delegate delegate =
        ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
      _ServerObjectInterfaceStub stub = new _ServerObjectInterfaceStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }
}
