package frontend.DMS_CORBA;

/**
* DMS_CORBA/ServerObjectInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerObjectInterface.idl
* Saturday, April 8, 2023 3:06:56 o'clock PM EDT
*/

public final class ServerObjectInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerObjectInterface value = null;

  public ServerObjectInterfaceHolder ()
  {
  }

  public ServerObjectInterfaceHolder (ServerObjectInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerObjectInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerObjectInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerObjectInterfaceHelper.type ();
  }

}
